Try to make ltp outputs in the console

diff --git a/centos_ci_build b/centos_ci_build
--- a/centos_ci_build
+++ b/centos_ci_build
@@ -16,17 +16,18 @@ make all >/dev/null
 echo "`date +%H:%M:%S` - $LTPtext installing"
 make install >/dev/null
 
-echo "`date +%H:%M:%S` - $LTPtext Starting LTP-Lite testsuite: This is expected to take 20-25 mins"
-/opt/ltp/runltplite.sh -l result.txt -p -q
+echo "`date +%H:%M:%S` - $LTPtext Starting $LTPtext: This is expected to take 20-25 mins"
+#/opt/ltp/runltplite.sh -l result.txt -p -q
+/opt/ltp/runltplite.sh -p -q
 
-ret_val=$(grep -c FAIL /opt/ltp/results/result.txt)
+#ret_val=$(grep -c FAIL /opt/ltp/results/result.txt)
 
-if [ $ret_val -gt 0 ]
-  then
-  echo "`date +%H:%M:%S` - $LTPtext The following tests FAILed: "
-  grep FAIL /opt/ltp/results/result.txt
-else
-  echo "`date +%H:%M:%S` - $LTPtext All tests completed successfully"
-fi
+#if [ $ret_val -gt 0 ]
+#  then
+#  echo "`date +%H:%M:%S` - $LTPtext The following tests FAILed: "
+#  grep FAIL /opt/ltp/results/result.txt
+#else
+#  echo "`date +%H:%M:%S` - $LTPtext All tests completed successfully"
+#fi
 
-exit $ret_val
+#exit $ret_val
